"""Initial candidate application and sync schema

Revision ID: 0001_initial
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('hubspot_contact_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('target_role', sa.String(length=50), nullable=False),
    sa.Column('role_detail', sa.String(length=200), nullable=True),
    sa.Column('experience_level', sa.String(length=40), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('portfolio_url', sa.String(length=2048), nullable=True),
    sa.Column('resume_url', sa.String(length=2048), nullable=True),
    sa.Column('compensation_expectations', sa.String(length=500), nullable=True),
    sa.Column('compensation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compensation_currency', sa.String(length=3), nullable=True),
    sa.Column('compensation_period', sa.String(length=20), nullable=True),
    sa.Column('availability', sa.String(length=500), nullable=True),
    sa.Column('fit_summary', sa.Text(), nullable=True),
    sa.Column('role_answers', sa.JSON(), nullable=False),
    sa.Column('consent_to_process', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('new_applicants','screening','interview','offered','hired','rejected','withdrawn')", name='ck_application_status'),
    sa.CheckConstraint("target_role IN ('engineering','design','marketing','operations','other')", name='ck_application_role'),
    sa.CheckConstraint('compensation_amount IS NULL OR compensation_amount >= 0', name='ck_compensation'),
    sa.CheckConstraint('experience_years IS NULL OR (experience_years >= 0 AND experience_years <= 80)', name='ck_experience_years'),
    sa.CheckConstraint('version >= 1', name='ck_application_version'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'target_role', name='uq_candidate_role')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index('ix_applications_status_created', ['status', 'created_at'], unique=False)

    op.create_table('intake_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'event_key', name='uq_intake_event')
    )
    op.create_table('status_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_events_application_id'), ['application_id'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('last_error', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state IN ('pending','processing','retry','succeeded','dead')", name='ck_sync_state'),
    sa.CheckConstraint("target IN ('hubspot','notion','zapier')", name='ck_sync_target'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'target', 'revision', name='uq_sync_revision')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_due', ['state', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_application_id'))
        batch_op.drop_index('ix_sync_due')

    op.drop_table('sync_jobs')
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_events_application_id'))

    op.drop_table('status_events')
    op.drop_table('intake_receipts')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_status_created')
        batch_op.drop_index(batch_op.f('ix_applications_candidate_id'))

    op.drop_table('applications')
    op.drop_table('candidates')
    # ### end Alembic commands ###
