"""Marketplace accounts jobs sessions and application snapshots

Revision ID: 0002_marketplace
Revises: 0001_initial
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_marketplace'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_buckets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_started_at'), ['started_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('seeker','employer')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id')
    )
    op.create_table('seeker_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=120), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.Column('role_detail', sa.String(length=200), nullable=True),
    sa.Column('experience_level', sa.String(length=40), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('portfolio_url', sa.String(length=2048), nullable=True),
    sa.Column('resume_url', sa.String(length=2048), nullable=True),
    sa.Column('availability', sa.String(length=500), nullable=True),
    sa.Column('compensation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compensation_currency', sa.String(length=3), nullable=True),
    sa.Column('compensation_period', sa.String(length=20), nullable=True),
    sa.Column('compensation_expectations', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('levels', sa.JSON(), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('work_mode', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('open','closed')", name='ck_job_status'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_employer_id'), ['employer_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('cover_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('employer_message', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('profile_snapshot', sa.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_candidate_role'), type_='unique')
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index('uq_candidate_job', ['candidate_id', 'job_id'], unique=True, sqlite_where=sa.text('job_id IS NOT NULL'), postgresql_where=sa.text('job_id IS NOT NULL'))
        batch_op.create_index('uq_candidate_legacy_role', ['candidate_id', 'target_role'], unique=True, sqlite_where=sa.text('job_id IS NULL'), postgresql_where=sa.text('job_id IS NULL'))
        batch_op.create_foreign_key('fk_applications_job', 'jobs', ['job_id'], ['id'])

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_candidate_user', ['user_id'])
        batch_op.create_foreign_key('fk_candidates_user', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.alter_column('actor',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    if op.get_bind().execute(sa.text('SELECT 1 FROM users LIMIT 1')).first():
        raise RuntimeError('Downgrade refused: marketplace accounts exist. Restore a backup instead.')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.alter_column('actor',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_candidates_user', type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_candidate_user', type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_applications_job', type_='foreignkey')
        batch_op.drop_index('uq_candidate_legacy_role', sqlite_where=sa.text('job_id IS NULL'), postgresql_where=sa.text('job_id IS NULL'))
        batch_op.drop_index('uq_candidate_job', sqlite_where=sa.text('job_id IS NOT NULL'), postgresql_where=sa.text('job_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_candidate_role'), ['candidate_id', 'target_role'])
        batch_op.drop_column('profile_snapshot')
        batch_op.drop_column('employer_message')
        batch_op.drop_column('cover_note')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_employer_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    op.drop_table('seeker_profiles')
    op.drop_table('employers')
    op.drop_table('users')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_started_at'))

    op.drop_table('rate_limit_buckets')
    # ### end Alembic commands ###
