// Open roles. Used to render the page, to match candidates, and as context for Fern.
// `area` and `levels` use the backend's values (see options.js). `skills` are
// lowercase keywords the matcher looks for in what candidates write.

export const roles = [
  {
    id: 'frontend-engineer',
    title: 'Frontend Engineer',
    area: 'engineering',
    levels: ['junior', 'mid', 'senior'],
    type: 'Full-time',
    location: 'Remote',
    summary: 'Build the booking flows and dashboards that thousands of studios use every day.',
    skills: ['javascript', 'typescript', 'react', 'vue', 'svelte', 'css', 'html', 'tailwind', 'accessibility', 'frontend'],
  },
  {
    id: 'backend-engineer',
    title: 'Backend Engineer',
    area: 'engineering',
    levels: ['mid', 'senior', 'lead'],
    type: 'Full-time',
    location: 'Remote',
    summary: 'Design reliable APIs, calendar sync and the payment plumbing behind every booking.',
    skills: ['python', 'node', 'go', 'java', 'sql', 'postgres', 'postgresql', 'api', 'fastapi', 'django', 'backend', 'aws'],
  },
  {
    id: 'engineering-intern',
    title: 'Software Engineering Intern',
    area: 'engineering',
    levels: ['intern', 'junior'],
    type: 'Internship · 6 months',
    location: 'Remote',
    summary: 'Pair with a mentor and ship real features from your second week.',
    skills: ['javascript', 'python', 'java', 'git', 'html', 'css', 'react', 'sql'],
  },
  {
    id: 'product-designer',
    title: 'Product Designer',
    area: 'design',
    levels: ['mid', 'senior'],
    type: 'Full-time',
    location: 'Remote',
    summary: 'Turn messy studio workflows into calm, simple screens, from research to polished UI.',
    skills: ['figma', 'prototyping', 'user research', 'ux', 'ui', 'design system', 'interaction design', 'usability'],
  },
  {
    id: 'brand-designer',
    title: 'Brand & Visual Designer',
    area: 'design',
    levels: ['junior', 'mid'],
    type: 'Full-time',
    location: 'Remote',
    summary: 'Shape how Fernway looks and sounds, from illustrations to launch campaigns.',
    skills: ['illustration', 'typography', 'branding', 'brand', 'visual', 'motion', 'canva', 'adobe', 'photoshop', 'illustrator'],
  },
  {
    id: 'growth-marketer',
    title: 'Growth Marketer',
    area: 'marketing',
    levels: ['junior', 'mid', 'senior'],
    type: 'Full-time',
    location: 'Remote',
    summary: 'Find the studios who need us, and help them fall for the product.',
    skills: ['seo', 'paid ads', 'ads', 'email', 'content', 'analytics', 'social', 'campaign', 'growth', 'lifecycle', 'conversion'],
  },
  {
    id: 'people-ops-coordinator',
    title: 'People & Operations Coordinator',
    area: 'operations',
    levels: ['junior', 'mid'],
    type: 'Full-time',
    location: 'Remote',
    summary: 'Keep hiring, onboarding and team rituals running smoothly as we grow.',
    skills: ['recruiting', 'onboarding', 'operations', 'hr', 'people', 'notion', 'hubspot', 'events', 'process', 'scheduling'],
  },
];
